"""API-level constants for FastAPI app and routers."""

APP_TITLE = "AI Job Finder API"
APP_VERSION = "1.0.0"

API_HOST_ENV = "API_HOST"
API_PORT_ENV = "API_PORT"
API_RELOAD_ENV = "API_RELOAD"
DEFAULT_API_HOST = "0.0.0.0"
DEFAULT_API_PORT = 8000
DEFAULT_API_RELOAD = False

API_V1_PREFIX = "/api/v1"
SEARCH_ENDPOINT = "/search"
SEARCH_TAG = "search"

MAX_VACANCY_RESULTS = 5
QUERY_MIN_LENGTH = 1

HTTP_BAD_REQUEST = 400
HTTP_NOT_FOUND = 404
HTTP_UNPROCESSABLE_ENTITY = 422
HTTP_INTERNAL_SERVER_ERROR = 500

ERROR_CODE_REQUEST_VALIDATION = "REQUEST_VALIDATION_ERROR"
ERROR_CODE_RESPONSE_VALIDATION = "RESPONSE_VALIDATION_ERROR"
ERROR_CODE_NOT_FOUND = "NOT_FOUND"
ERROR_CODE_HTTP = "HTTP_ERROR"
ERROR_CODE_INTERNAL = "INTERNAL_SERVER_ERROR"

ERROR_MESSAGE_REQUEST_VALIDATION = "Incoming request validation failed."
ERROR_MESSAGE_RESPONSE_VALIDATION = "Outgoing response validation failed."
ERROR_MESSAGE_NOT_FOUND = "Requested endpoint was not found."
ERROR_MESSAGE_HTTP = "HTTP request failed."
ERROR_MESSAGE_INTERNAL = "Unexpected server error occurred."
ERROR_MESSAGE_BLANK_QUERY = "Query must not be blank."
ERROR_MESSAGE_SEARCH_UNAVAILABLE = "Search service is temporarily unavailable."
