"""Frontend constants for backend API integration."""

BACKEND_API_URL_ENV = "BACKEND_API_URL"
DEFAULT_BACKEND_API_URL = "http://localhost:8000"
SEARCH_ENDPOINT = "/api/v1/search"

BACKEND_TIMEOUT_SECONDS = 20.0
BACKEND_REQUEST_RETRY_COUNT = 1

HTTP_STATUS_NOT_FOUND = 404
HTTP_STATUS_SERVER_ERROR_MIN = 500

SEARCH_QUERY_MIN_LENGTH = 1
SEARCH_QUERY_MAX_LENGTH = 2000
